services:
  my-redis:
    image: redis:7.2.4
    command:
      ["sh", "-c", 'exec redis-server --port 6379 --requirepass "$$REDIS_PASSWORD"']
    healthcheck:
      test: [ "CMD-SHELL", 'redis-cli --no-auth-warning -a "$$REDIS_PASSWORD" ping | grep -q PONG' ]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - chat-network

  db:
    image: mysql:8.4.10
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 -u root -p"$$MYSQL_ROOT_PASSWORD" --silent']
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s
    networks:
      - chat-network

  chat-app:
    depends_on:
      my-redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - chat-network

  celery:
    depends_on:
      my-redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: [ "celery", "-A", "chat_connect", "worker", "--loglevel=info"]
    networks:
      - chat-network

  celery-beat:
    depends_on:
      my-redis:
        condition: service_healthy
      db:
        condition: service_healthy
      celery:
        condition: service_started
    command: [ "celery", "-A", "chat_connect", "beat", "--loglevel=info" ]
    networks:
      - chat-network

volumes:
  db_data:

networks:
  chat-network:
    driver: bridge