services:
  my-redis:
    ports:
      - "6379:6379"
    env_file:
      - .envs/development/redis.env

  db:
    ports:
      - "3306:3306"
    env_file:
      - .envs/development/mysql.env

  chat-app:
    build:
      context: .
      dockerfile: deployments/development/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .envs/development/django.env
      - .envs/development/docker.env

  celery:
    build:
      context: .
      dockerfile: deployments/development/Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .envs/development/django.env
      - .envs/development/docker.env

  celery-beat:
    build:
      context: .
      dockerfile: deployments/development/Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .envs/development/django.env
      - .envs/development/docker.env
