version: "2"
services:
  my-redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      # Mount the custom redis.conf file into the container
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  chat-app:
    build:
      context: .
      dockerfile: deployments/${ENVIRON}/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - my-redis
    environment:
      - REDIS_HOST=my-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  celery:
    build:
      context: .
      dockerfile: deployments/${ENVIRON}/Dockerfile
    depends_on:
      - my-redis
      - chat-app
    volumes:
      - .:/usr/src/app
    environment:
      - REDIS_HOST=my-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB_CELERY=2
    command: ["celery", "-A", "chat_connect", "worker", "--loglevel=info", "--concurrency=4"]
