services:
  my-redis:
    env_file:
      - .envs/production/redis.env
    restart: unless-stopped

  db:
    env_file:
      - .envs/production/mysql.env
    restart: unless-stopped

  chat-app:
    build:
      context: .
      dockerfile: deployments/production/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .envs/production/django.env
      - .envs/production/docker.env
    volumes:
      - ./prod_static:/usr/src/app/chat_connect/prod_static
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: deployments/production/Dockerfile
    env_file:
      - .envs/production/django.env
      - .envs/production/docker.env
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: deployments/production/Dockerfile
    env_file:
      - .envs/production/django.env
      - .envs/production/docker.env
    restart: unless-stopped
