REDIS_USERNAME_KEY = "asgi:usernames"
REDIS_GROUPS_KEY = "asgi:group"
TASK_LOCK_KEY = "send_random_messages_task_lock"
HAS_USERS = "has_users"
USER_IDS = "user_ids"
USER_PROMOTIONAL_IDS = "user_promotional_ids"
TOPIC_IDS = "topic_ids"
TOPIC_PROMOTIONAL_IDS = "topic_promotional_ids"
