# Generated by Django 4.2.16 on 2026-05-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processed", "Processed"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        default="processed",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StripeInvoiceNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_invoice_id", models.CharField(max_length=255)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("payment_succeeded", "Payment succeeded"),
                            ("payment_failed", "Payment failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("stripe_invoice_id", "email_type")},
            },
        ),
    ]
