# Generated by Django 4.2.16 on 2026-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_stripewebhookevent_stripeinvoicenotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
