# Generated by Django 4.2.16 on 2026-05-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0003_alter_usersubscription_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
