# Generated by Django 4.2.16 on 2026-06-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_stripeinvoicenotification_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
