# Generated by Django 4.2.16 on 2026-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_usersubscription_current_period_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripewebhookevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("ignored", "Ignored"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
