version: "2"
services:
  my-redis-tests:
    image: redis:7.2.4
    ports:
      - "6380:6379"
    #volumes:
      # Mount the custom redis.conf file into the container
      # - redis.conf:/usr/local/etc/redis/redis.conf
    #command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "6380"]
    command: ["redis-server", "--port", "6380", "--requirepass", "redis-test"]
  test:
    build:
      context: ../../../
      dockerfile: deployments/development/testing/Dockerfile-tests
    volumes:
      - ../../../:/usr/src/app-tests
    depends_on:
      - my-redis-tests
    environment:
      - REDIS_HOST=my-redis-tests
      - REDIS_PORT=6380
      - REDIS_PASSWORD=redis-test
    command: python manage.py test apps.chat --settings=chat_connect.settings.settings_tests
