FROM python:3.12-slim-bookworm

WORKDIR /usr/src/app-tests

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app
COPY .. .

CMD ["python", "manage.py", "test", "apps.chat", "apps.integrations", "apps.subscriptions", "apps.users", "--settings=chat_connect.settings.settings_tests"]
