name: "🛠️ Setup Python and Project Dependencies"
description: "Sets up Python 3.9 and installs all required project dependencies, including development packages, using Pipenv. Ideal for preparing the environment for tests or CI workflows."

runs:
  using: "composite"
  steps:
    - name: 🐍 Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: 📦 Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
      shell: bash

    - name: 📦 Install Dependencies with Pipenv
      run: |
        pipenv install --dev
      shell: bash
