name: "🛠️ Setup Python and Project Dependencies"
description: "Sets up Python 3.12 and installs all required project dependencies, including development packages, using Pipenv. Ideal for preparing the environment for tests or CI workflows."


runs:
  using: "composite"
  steps:
    - name: 🐍 Set up Python 3.12
      uses: actions/setup-python@v7
      with:
        python-version: 3.12
        cache: "pipenv"
        cache-dependency-path: "Pipfile.lock"

    - name: 📦 Install Pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install "pipenv==2026.7.1"
      shell: bash

    - name: 🔒 Verify Pipfile.lock
      shell: bash
      run: pipenv verify

    - name: 📦 Install development dependencies
      shell: bash
      run: pipenv sync --dev
