name: 🚀 Deploy to VPS

on:
  workflow_dispatch:
    inputs:
      run_collectstatic:
        description: "Run collectstatic?"
        required: false
        default: false
        type: boolean
      clear_redis:
        description: "Clear redis?"
        required: false
        default: false
        type: boolean
      run_migrations:
        description: "Run migrations?"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROJECT_DIR: "projects/chatea-conecta"
          BRANCH: "master"
          RUN_COLLECTSTATIC: ${{ inputs.run_collectstatic }}
          CLEAR_REDIS: ${{ inputs.clear_redis }}
          RUN_MIGRATIONS: ${{ inputs.run_migrations }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_DIR,BRANCH,RUN_COLLECTSTATIC,CLEAR_REDIS,RUN_MIGRATIONS,REDIS_PASSWORD
          script: |
            echo "Navigating to project directory..."
            cd $PROJECT_DIR || { echo "Project directory not found. Exiting."; exit 1; }

            echo "Pulling latest code from branch $BRANCH..."
            git fetch origin $BRANCH || { echo "Git fetch failed. Exiting."; exit 1; }
            git reset --hard origin/$BRANCH || { echo "Git reset failed. Exiting."; exit 1; }

            echo "Building Docker containers..."
            docker compose -f docker-compose.prod.yml build || { echo "Docker build failed. Exiting."; exit 1; }

            echo "Restarting Docker services..."
            docker compose -f docker-compose.prod.yml down || { echo "Docker shutdown failed. Exiting."; exit 1; }
            docker compose -f docker-compose.prod.yml up -d || { echo "Docker startup failed. Exiting."; exit 1; }
            
            # Run compilemessages
            echo "Compiling messages..."
            docker exec chat-app python manage.py compilemessages || { echo "Compilemessages failed. Exiting."; exit 1; }
            
            # Clear Redis if input is True
            if [ "$CLEAR_REDIS" = "true" ]; then
              echo "Clearing Redis database..."
              docker exec redis redis-cli -a $REDIS_PASSWORD FLUSHALL || { echo "Redis clearing failed. Exiting."; exit 1; }
            fi
            
            # Run migrations if input is true
            if [ "$RUN_MIGRATIONS" = "true" ]; then
              echo "Running database migrations..."
              docker exec chat-app python manage.py migrate --noinput || { echo "Database migrations failed. Exiting."; exit 1; }
            fi
            
            # Run collectstatic if input is true
            if [ "$RUN_COLLECTSTATIC" = "true" ]; then
              echo "Collecting static files..."
              docker exec chat-app python manage.py collectstatic --noinput || { echo "Collectstatic failed. Exiting."; exit 1; }
            fi

            echo "Restarting NGINX..."
            sudo systemctl restart nginx || { echo "NGINX restart failed. Exiting."; exit 1; }

            echo "Deployment complete!"