name: 🚀 Deploy to VPS

on:
  workflow_dispatch:
    inputs:
      clear_redis:
        description: "Clear redis?"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        env:
          PROJECT_DIR: "projects/chatea-conecta"
          BRANCH: "master"
          CLEAR_REDIS: ${{ inputs.clear_redis }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 60m
          envs: PROJECT_DIR,BRANCH,CLEAR_REDIS,REDIS_PASSWORD
          script: |
            echo "Navigating to project directory..."
            cd $PROJECT_DIR || { echo "Project directory not found. Exiting."; exit 1; }

            echo "Pulling latest code from branch $BRANCH..."
            git fetch origin $BRANCH || { echo "Git fetch failed. Exiting."; exit 1; }
            git reset --hard origin/$BRANCH || { echo "Git reset failed. Exiting."; exit 1; }

            echo "Building Docker containers..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml build || { echo "Docker build failed. Exiting."; exit 1; }

            echo "Stopping Docker services..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml down || { echo "Docker shutdown failed. Exiting."; exit 1; }

            # `run` starts db and my-redis first and waits for their healthchecks.
            echo "Running database migrations..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm -T chat-app python manage.py migrate --noinput || { echo "Database migrations failed. Exiting."; exit 1; }

            echo "Collecting static files..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml run --rm -T chat-app python manage.py collectstatic --noinput || { echo "Collectstatic failed. Exiting."; exit 1; }

            echo "Starting Docker services..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d || { echo "Docker startup failed. Exiting."; exit 1; }

            # Clear Redis if input is True
            if [ "$CLEAR_REDIS" = "true" ]; then
              echo "Clearing Redis database..."
              docker compose -f docker-compose.yml -f docker-compose.prod.yml exec -T my-redis redis-cli -a $REDIS_PASSWORD FLUSHALL || { echo "Redis clearing failed. Exiting."; exit 1; }
            fi

            echo "Restarting NGINX..."
            sudo systemctl restart nginx || { echo "NGINX restart failed. Exiting."; exit 1; }

            echo "Deployment complete!"
