name: 🔍 Validate Code and Migrations

permissions:
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: 🧪 Tests and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v7

      - name: 🛠️ Setup Project Environment
        uses: ./.github/actions/setup-environment-test
        with:
          install-dev: "true"

      - name: 🧪 Run Tests with Coverage
        run: |
            pipenv run coverage run \
            --source="apps.chat" \
            manage.py test apps.chat \
            --settings=chat_connect.settings.settings_tests

            pipenv run coverage report --show-missing

  migrations:
    name: 📋 Check Pending Migrations
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v7

      - name: 🛠️ Setup Project Environment
        uses: ./.github/actions/setup-environment-test
        with:
          install-dev: "false"

      - name: 📋 Check for Pending Migrations
        run: |
          pipenv run python manage.py makemigrations \
            --check \
            --dry-run \
            --settings=chat_connect.settings.settings_tests

  check-deploy:
    name: 🚀 Deployment Checks
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v7

      - name: 🛠️ Setup Project Environment
        uses: ./.github/actions/setup-environment-test
        with:
          install-dev: "false"

      - name: ✅ Run Django Deployment Checks
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          SKIP_CLOUDWATCH: "1"
        run: |
          pipenv run python manage.py check --deploy --settings=chat_connect.settings.settings_production
