# Generated by Django 4.2.15 on 2024-11-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_topic_is_promotional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="is_promotional",
        ),
        migrations.AddField(
            model_name="conversationflow",
            name="is_promotional",
            field=models.BooleanField(default=False),
        ),
    ]
